version: '2'
services:
    api:
        build: ./src/api
        # volumes:
        #     - .:/usr/app/
        #     - /usr/app/node_modules
        ports:
            - "3000:8080"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "sql_password1106"
            ACCEPT_EULA: "Y"
            